events {}

http {
    server {
        listen 80;
        server_name localhost;
        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, PATCH, DELETE, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Content-Type, Authorization" always;

        location /api/account/ {
            proxy_pass http://cs-trading-platform-account-service:3001/;
        }

        location /api/finance/ {
            proxy_pass http://cs-trading-platform-order-service:3002/;
        }

        location /api/matching/ {
            proxy_pass http://cs-trading-platform-matching-service:3003/;
        }
    }
}