events {}

http {
    server {
        listen 80;
        server_name localhost;
        location /account/ {
            proxy_pass http://cs-trading-platform-account-service:3001/;
        }
        location /finance/ {
            proxy_pass http://cs-trading-platform-order-service:3002/;
        }
        location /matching/ {
            proxy_pass http://cs-trading-platform-matching-service:3003/;
        }
    }
}